# Generated by Django 5.0.2 on 2025-06-23 08:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebHookApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("url", models.CharField(max_length=256, verbose_name="Ссылка")),
                ("secret_key", models.CharField(max_length=512, verbose_name="Секретный ключ")),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="События",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приложение Вебхуков",
                "verbose_name_plural": "Приложения Вебхуков",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="WebHookLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(max_length=256, verbose_name="Ивент")),
                ("action", models.CharField(max_length=256, verbose_name="Событие")),
                ("data", models.JSONField(verbose_name="Отправленные данные")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ожидание"), ("success", "Успешно"), ("failed", "Ошибка")],
                        default="pending",
                        max_length=256,
                    ),
                ),
                ("detail", models.JSONField(blank=True, null=True)),
                ("url", models.CharField(max_length=200, verbose_name="Ссылка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("retries", models.SmallIntegerField(default=0)),
                (
                    "app",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="whook.webhookapp"),
                ),
            ],
            options={
                "verbose_name": "Логи отправки данных",
                "verbose_name_plural": "Логи отправки данных",
                "ordering": ("-created_at",),
            },
        ),
    ]
