# Generated by Django 5.0.2 on 2025-09-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whook', '0002_alter_webhooklog_detail_alter_webhooklog_retries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
    ]
