# Generated by Django 5.2.6 on 2026-01-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whook', '0003_alter_webhooklog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookapp',
            name='selected_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Словарь вида {event_code: [field1, field2, ...]}', verbose_name='Выбранные поля для событий'),
        ),
    ]
