# Generated by Django 4.2.13 on 2026-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whook', '0004_webhookapp_selected_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookapp',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Пример: {"article":{"origin_source": "infocenter","url": 123,},"info_unit":{"status": "approved"},} Вебхук отправляется, если значения указанных полей совпадают. Если поле отсутствует в сериализованных для отправки данных, условие по нему пропускается.', verbose_name='Условия отбора сущностей для отправки вебхуков'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время события'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='instance_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID экземпляра'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован для повтора'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='next_retry_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время следующей попытки отправки'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последней отправки'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('success', 'Успешно'), ('has_newer_success', 'Более новый лог был успешным'), ('failed', 'Ошибка')], default='pending', max_length=256, verbose_name='Статус отправки'),
        ),
    ]
